In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, classification_report

import xgboost as xgb
import optuna

from tqdm import tqdm

In [2]:
train_df = pd.read_csv("training(2003-2023).csv")
test_df = pd.read_csv("test(2024-25).csv")

print(train_df.shape)
print(test_df.shape)

(20988361, 14)
(1182188, 14)

In [3]:
FEATURES = [
    "CHLOR_A",
    "day_sin",
    "day_cos",
    "month_sin",
    "month_cos",
    "LAT_scaled",
    "LON_scaled"
]

TARGET = "PHYTOBLOOM"

In [4]:
X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

In [31]:
def objective(trial):

    # params = {

    #     "objective": "multi:softprob",
    #     "num_class": 3,

    #     "n_estimators":
    #         trial.suggest_int(
    #             "n_estimators",
    #             100,
    #             500,
    #             step=50
    #         ),

    #     "max_depth":
    #         trial.suggest_int(
    #             "max_depth",
    #             4,
    #             12
    #         ),

    #     "learning_rate":
    #         trial.suggest_float(
    #             "learning_rate",
    #             0.01,
    #             0.3,
    #             log=True
    #         ),

    #     "subsample":
    #         trial.suggest_float(
    #             "subsample",
    #             0.6,
    #             1.0
    #         ),

    #     "colsample_bytree":
    #         trial.suggest_float(
    #             "colsample_bytree",
    #             0.6,
    #             1.0
    #         ),

    #     "min_child_weight":
    #         trial.suggest_int(
    #             "min_child_weight",
    #             1,
    #             20
    #         ),

    #     "gamma":
    #         trial.suggest_float(
    #             "gamma",
    #             1e-5,
    #             1.0,
    #             log=True
    #         ),

    #     "lambda":
    #         trial.suggest_float(
    #             "lambda",
    #             1e-3,
    #             10,
    #             log=True
    #         ),

    #     "alpha":
    #         trial.suggest_float(
    #             "alpha",
    #             1e-3,
    #             5,
    #             log=True
    #         ),

    #     "grow_policy":
    #         trial.suggest_categorical(
    #             "grow_policy",
    #             ["depthwise", "lossguide"]
    #         ),

    #     "tree_method": "hist",

    #     "random_state": 42,

    #     "n_jobs": -1
    # }

    # params = {

    #     "n_estimators":
    #     trial.suggest_int(
    #         "n_estimators",
    #         30,
    #         80,
    #         step=10
    #     ),

    #     "max_depth":
    #     trial.suggest_int(
    #         "max_depth",
    #         1,
    #         6
    #     ),

    #     "learning_rate":
    #     trial.suggest_float(
    #         "learning_rate",
    #         0.03,
    #         0.10
    #     ),

    #     "min_child_weight":
    #     trial.suggest_int(
    #         "min_child_weight",
    #         10,
    #         18
    #     ),

    #     "subsample":
    #     trial.suggest_float(
    #         "subsample",
    #         0.50,
    #         0.85
    #     ),

    #     "colsample_bytree":
    #     trial.suggest_float(
    #         "colsample_bytree",
    #         0.65,
    #         0.80
    #     ),

    #     "gamma":
    #     trial.suggest_float(
    #         "gamma",
    #         0.0,
    #         0.05
    #     ),

    #     "lambda":
    #     trial.suggest_float(
    #         "lambda",
    #         0.001,
    #         0.01,
    #         log=True
    #     ),

    #     "alpha":
    #     trial.suggest_float(
    #         "alpha",
    #         0.001,
    #         0.02,
    #         log=True
    #     )
    # }

    params = {

        "n_estimators":
        trial.suggest_int(
            "n_estimators",
            10,
            70,
            step=10
        ),

        "max_depth":
        trial.suggest_int(
            "max_depth",
            2,
            8
        ),

        "learning_rate":
        trial.suggest_float(
            "learning_rate",
            0.03,
            0.15
        ),

        "min_child_weight":
        trial.suggest_int(
            "min_child_weight",
            10,
            18
        ),

        "subsample":
        trial.suggest_float(
            "subsample",
            0.50,
            0.85
        ),

        "colsample_bytree":
        trial.suggest_float(
            "colsample_bytree",
            0.65,
            0.80
        ),

        "gamma":
        trial.suggest_float(
            "gamma",
            0.0,
            0.05
        ),

        "lambda":
        trial.suggest_float(
            "lambda",
            0.001,
            0.01,
            log=True
        ),

        "alpha":
        trial.suggest_float(
            "alpha",
            0.001,
            0.02,
            log=True
        )
    }

    skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

    scores = []

    for train_idx, val_idx in skf.split(X_train,y_train):

        X_tr = X_train.iloc[train_idx]
        X_val = X_train.iloc[val_idx]

        y_tr = y_train.iloc[train_idx]
        y_val = y_train.iloc[val_idx]

        model = xgb.XGBClassifier(
            **params
        )

        model.fit(
            X_tr,
            y_tr,
            verbose=False
        )

        pred = model.predict(X_val)

        macro_f1 = f1_score(
            y_val,
            pred,
            average="macro"
        )

        scores.append(
            macro_f1
        )

    return np.mean(scores)

In [13]:
study = optuna.create_study(direction="maximize")

study.optimize(
    objective,
    n_trials=20,
    show_progress_bar=True
)

[I 2026-06-24 12:09:18,872] A new study created in memory with name: no-name-7908a2dc-fe5b-4a48-9e58-c05baf73a499

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-06-24 12:33:59,945] Trial 0 finished with value: 0.9347852268967994 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.24185210764823528, 'subsample': 0.6460050564514498, 'colsample_bytree': 0.6597355908371025, 'min_child_weight': 13, 'gamma': 1.0457661097563821e-05, 'lambda': 1.844295039318334, 'alpha': 1.4830214178222523, 'grow_policy': 'depthwise'}. Best is trial 0 with value: 0.9347852268967994.
[I 2026-06-24 14:09:40,257] Trial 1 finished with value: 0.9385135108679756 and parameters: {'n_estimators': 500, 'max_depth': 12, 'learning_rate': 0.016281695396146115, 'subsample': 0.7507463273900259, 'colsample_bytree': 0.83282516039172, 'min_child_weight': 18, 'gamma': 0.004473123047487134, 'lambda': 0.10147397202253616, 'alpha': 0.001058089429099311, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 0.9385135108679756.
[I 2026-06-24 15:17:10,479] Trial 2 finished with value: 0.9351980970250476 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.012946962043428599, 'subsample': 0.8627076055040419, 'colsample_bytree': 0.6038916074379638, 'min_child_weight': 15, 'gamma': 1.083383538227736e-05, 'lambda': 1.36494953031014, 'alpha': 0.02092210337891527, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 0.9385135108679756.
[I 2026-06-24 16:19:53,648] Trial 3 finished with value: 0.9415300193945584 and parameters: {'n_estimators': 300, 'max_depth': 12, 'learning_rate': 0.13111566298616767, 'subsample': 0.7190571132490522, 'colsample_bytree': 0.7739382178389024, 'min_child_weight': 20, 'gamma': 2.1255049880197123e-05, 'lambda': 0.007247839671488724, 'alpha': 4.737288423982548, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 17:27:22,980] Trial 4 finished with value: 0.9356910332002114 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.052635568793306296, 'subsample': 0.8055436505071889, 'colsample_bytree': 0.6200581420011342, 'min_child_weight': 7, 'gamma': 7.830650145978563e-05, 'lambda': 0.02237637811697417, 'alpha': 0.002420321661230817, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 18:04:55,432] Trial 5 finished with value: 0.9322360948307298 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.02465508489590683, 'subsample': 0.7027511765276612, 'colsample_bytree': 0.8299362274764475, 'min_child_weight': 11, 'gamma': 9.990238806954435e-05, 'lambda': 3.2005355394629458, 'alpha': 0.2855098565998752, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 19:35:49,392] Trial 6 finished with value: 0.9372172992985556 and parameters: {'n_estimators': 350, 'max_depth': 12, 'learning_rate': 0.010202316943954386, 'subsample': 0.7390544437281439, 'colsample_bytree': 0.8570162618100405, 'min_child_weight': 3, 'gamma': 0.00044403326234426283, 'lambda': 0.004771575457130187, 'alpha': 0.016010824283814794, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 20:46:50,876] Trial 7 finished with value: 0.9372195809346703 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.022870452493034658, 'subsample': 0.9006972621452415, 'colsample_bytree': 0.81747480833777, 'min_child_weight': 15, 'gamma': 0.2547196634256776, 'lambda': 4.164777951504221, 'alpha': 0.13017670676452572, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 21:24:01,875] Trial 8 finished with value: 0.9351107682123784 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.0237354128527231, 'subsample': 0.9371932967690084, 'colsample_bytree': 0.918926379623269, 'min_child_weight': 7, 'gamma': 0.003952950606980829, 'lambda': 8.761955817714503, 'alpha': 0.01017969374173996, 'grow_policy': 'lossguide'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 21:41:16,455] Trial 9 finished with value: 0.935157878665704 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.051940076603208984, 'subsample': 0.7041731036301319, 'colsample_bytree': 0.8604688693111179, 'min_child_weight': 6, 'gamma': 1.2113116282096954e-05, 'lambda': 0.006469849616673605, 'alpha': 0.1298300747045306, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-24 22:28:55,866] Trial 10 finished with value: 0.9345247713851933 and parameters: {'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.2941704469507253, 'subsample': 0.9979086080959039, 'colsample_bytree': 0.7291319233748006, 'min_child_weight': 18, 'gamma': 0.9767100841240641, 'lambda': 0.1846059864885968, 'alpha': 4.742300664592174, 'grow_policy': 'lossguide'}. Best is trial 3 with value: 0.9415300193945584.
[I 2026-06-25 00:11:25,633] Trial 11 finished with value: 0.9416493375097081 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.10283485909937976, 'subsample': 0.7721926455672589, 'colsample_bytree': 0.7472270919059127, 'min_child_weight': 20, 'gamma': 0.025503129349049834, 'lambda': 0.06361591687591016, 'alpha': 0.0018876260032686936, 'grow_policy': 'lossguide'}. Best is trial 11 with value: 0.9416493375097081.
[I 2026-06-25 01:06:13,796] Trial 12 finished with value: 0.9403150461139107 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.13296805098284337, 'subsample': 0.6261999483687449, 'colsample_bytree': 0.7317018155373636, 'min_child_weight': 20, 'gamma': 0.03603547810903342, 'lambda': 0.03356908235345776, 'alpha': 0.7839748984268632, 'grow_policy': 'lossguide'}. Best is trial 11 with value: 0.9416493375097081.
[I 2026-06-25 02:36:34,323] Trial 13 finished with value: 0.9419768277104339 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.1285015207188169, 'subsample': 0.8212058613289471, 'colsample_bytree': 0.7464018154653, 'min_child_weight': 20, 'gamma': 0.014042790574294238, 'lambda': 0.0011519711333389526, 'alpha': 0.04562230775853178, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 04:03:06,233] Trial 14 finished with value: 0.9400159466068987 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.090132010740936, 'subsample': 0.813194702515203, 'colsample_bytree': 0.70042219778368, 'min_child_weight': 17, 'gamma': 0.02560601297444448, 'lambda': 0.001388200781258204, 'alpha': 0.0053880187441551234, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 05:22:40,344] Trial 15 finished with value: 0.9407013495632747 and parameters: {'n_estimators': 450, 'max_depth': 11, 'learning_rate': 0.07122642955872016, 'subsample': 0.8064322825402316, 'colsample_bytree': 0.7707279211949348, 'min_child_weight': 20, 'gamma': 0.02723175567994205, 'lambda': 0.0011201140508720103, 'alpha': 0.04810311406383805, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 06:42:08,562] Trial 16 finished with value: 0.9407657980917662 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.18320491318285406, 'subsample': 0.8597242570396437, 'colsample_bytree': 0.9656795297502843, 'min_child_weight': 16, 'gamma': 0.0032804888511584434, 'lambda': 0.3866751665080614, 'alpha': 0.003773598412386531, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 08:03:10,448] Trial 17 finished with value: 0.9408752696033107 and parameters: {'n_estimators': 450, 'max_depth': 11, 'learning_rate': 0.10246819619258753, 'subsample': 0.7881417762108076, 'colsample_bytree': 0.6725089344827004, 'min_child_weight': 12, 'gamma': 0.13893755258617455, 'lambda': 0.029468964718451483, 'alpha': 0.03610160083347033, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 09:02:49,144] Trial 18 finished with value: 0.9366011180029534 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.046667606209161314, 'subsample': 0.8623020435100521, 'colsample_bytree': 0.770760438644785, 'min_child_weight': 18, 'gamma': 0.0012258223284916318, 'lambda': 0.2838352877811961, 'alpha': 0.0013858512129267427, 'grow_policy': 'lossguide'}. Best is trial 13 with value: 0.9419768277104339.
[I 2026-06-25 11:11:14,430] Trial 19 finished with value: 0.9419934990253955 and parameters: {'n_estimators': 400, 'max_depth': 11, 'learning_rate': 0.160150368880871, 'subsample': 0.6798136276263954, 'colsample_bytree': 0.7243238118279334, 'min_child_weight': 14, 'gamma': 0.014344298946540327, 'lambda': 0.0027281560811716794, 'alpha': 0.007634436209519525, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 0.9419934990253955.

In [15]:
print("Best Macro F1:")
print(study.best_value)

print("\nBest Parameters:")
study.best_params

Best Macro F1:
0.9419934990253955

Best Parameters:

{'n_estimators': 400,
 'max_depth': 11,
 'learning_rate': 0.160150368880871,
 'subsample': 0.6798136276263954,
 'colsample_bytree': 0.7243238118279334,
 'min_child_weight': 14,
 'gamma': 0.014344298946540327,
 'lambda': 0.0027281560811716794,
 'alpha': 0.007634436209519525,
 'grow_policy': 'lossguide'}

In [18]:
study2 = optuna.create_study(direction="maximize")

study2.optimize(
    objective,
    n_trials=20,
    show_progress_bar=True
)

[I 2026-06-27 03:22:15,259] A new study created in memory with name: no-name-b8207c98-981f-484a-9cd5-a090f5b84dd0

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-06-27 03:34:13,691] Trial 0 finished with value: 0.9121968687854963 and parameters: {'n_estimators': 40, 'max_depth': 2, 'learning_rate': 0.047914439391425825, 'min_child_weight': 11, 'subsample': 0.6267326399623052, 'colsample_bytree': 0.6981529849777277, 'gamma': 0.02205392010037094, 'lambda': 0.0012070757607308567, 'alpha': 0.011698902022926278}. Best is trial 0 with value: 0.9121968687854963.
[I 2026-06-27 04:00:09,233] Trial 1 finished with value: 0.9301283120526602 and parameters: {'n_estimators': 80, 'max_depth': 2, 'learning_rate': 0.08883302285030262, 'min_child_weight': 16, 'subsample': 0.5653541875182522, 'colsample_bytree': 0.7660284603044558, 'gamma': 0.0330318336100936, 'lambda': 0.00921567332126062, 'alpha': 0.005312820857270492}. Best is trial 1 with value: 0.9301283120526602.
[I 2026-06-27 04:35:36,503] Trial 2 finished with value: 0.9288983367403685 and parameters: {'n_estimators': 40, 'max_depth': 3, 'learning_rate': 0.07508371939364725, 'min_child_weight': 12, 'subsample': 0.5283048431362274, 'colsample_bytree': 0.6581345014882255, 'gamma': 0.004088421271824044, 'lambda': 0.0025384567437814498, 'alpha': 0.005635795046231448}. Best is trial 1 with value: 0.9301283120526602.
[I 2026-06-27 04:58:21,974] Trial 3 finished with value: 0.6151972699091272 and parameters: {'n_estimators': 30, 'max_depth': 1, 'learning_rate': 0.0523406323085359, 'min_child_weight': 16, 'subsample': 0.8273780837042835, 'colsample_bytree': 0.662650081304951, 'gamma': 0.04051773317773469, 'lambda': 0.00807123268460583, 'alpha': 0.00435497870240948}. Best is trial 1 with value: 0.9301283120526602.
[I 2026-06-27 05:19:44,947] Trial 4 finished with value: 0.9300648745944466 and parameters: {'n_estimators': 80, 'max_depth': 3, 'learning_rate': 0.057828971070595384, 'min_child_weight': 18, 'subsample': 0.7931620657410965, 'colsample_bytree': 0.6841123468036936, 'gamma': 0.028399360378139272, 'lambda': 0.0016148671506965573, 'alpha': 0.0060484790793749015}. Best is trial 1 with value: 0.9301283120526602.
[I 2026-06-27 05:35:25,845] Trial 5 finished with value: 0.9315115009897491 and parameters: {'n_estimators': 70, 'max_depth': 4, 'learning_rate': 0.08874258021258621, 'min_child_weight': 14, 'subsample': 0.574721597821919, 'colsample_bytree': 0.6638534530246589, 'gamma': 0.014167545440258895, 'lambda': 0.002373541914648246, 'alpha': 0.015736698020563114}. Best is trial 5 with value: 0.9315115009897491.
[I 2026-06-27 05:52:30,595] Trial 6 finished with value: 0.930876569671468 and parameters: {'n_estimators': 80, 'max_depth': 3, 'learning_rate': 0.06015295446553624, 'min_child_weight': 15, 'subsample': 0.5912323063801345, 'colsample_bytree': 0.7553424885366048, 'gamma': 0.005627175473255847, 'lambda': 0.0015825990858487733, 'alpha': 0.017852368390752923}. Best is trial 5 with value: 0.9315115009897491.
[I 2026-06-27 06:07:28,207] Trial 7 finished with value: 0.9298564543611306 and parameters: {'n_estimators': 80, 'max_depth': 3, 'learning_rate': 0.0431793931459397, 'min_child_weight': 10, 'subsample': 0.812386858235015, 'colsample_bytree': 0.7935503953186083, 'gamma': 0.024075644986029505, 'lambda': 0.0016019753000530634, 'alpha': 0.016751749601266474}. Best is trial 5 with value: 0.9315115009897491.
[I 2026-06-27 14:30:11,331] Trial 8 finished with value: 0.6151972699091272 and parameters: {'n_estimators': 40, 'max_depth': 1, 'learning_rate': 0.030289116470407433, 'min_child_weight': 11, 'subsample': 0.5098667271707499, 'colsample_bytree': 0.6575739004563335, 'gamma': 0.0468690640854068, 'lambda': 0.003703848498903006, 'alpha': 0.003064625332432852}. Best is trial 5 with value: 0.9315115009897491.
[I 2026-06-27 14:37:57,607] Trial 9 finished with value: 0.9172130001533538 and parameters: {'n_estimators': 60, 'max_depth': 1, 'learning_rate': 0.052343051931194026, 'min_child_weight': 10, 'subsample': 0.7288546194246157, 'colsample_bytree': 0.7986990649674337, 'gamma': 0.024216669644396234, 'lambda': 0.007691887241150601, 'alpha': 0.01896657317068309}. Best is trial 5 with value: 0.9315115009897491.
[I 2026-06-27 14:46:47,686] Trial 10 finished with value: 0.9317108136529069 and parameters: {'n_estimators': 60, 'max_depth': 4, 'learning_rate': 0.09129885166497022, 'min_child_weight': 13, 'subsample': 0.681584734221115, 'colsample_bytree': 0.7198187160818716, 'gamma': 0.01307374795389955, 'lambda': 0.004303189354202839, 'alpha': 0.0010427740798770065}. Best is trial 10 with value: 0.9317108136529069.
[I 2026-06-27 14:55:42,235] Trial 11 finished with value: 0.9317723770917127 and parameters: {'n_estimators': 60, 'max_depth': 4, 'learning_rate': 0.09713227563914609, 'min_child_weight': 13, 'subsample': 0.6711925232355832, 'colsample_bytree': 0.7176672280645789, 'gamma': 0.013214998237066953, 'lambda': 0.004296019431584893, 'alpha': 0.0010097850932629607}. Best is trial 11 with value: 0.9317723770917127.
[I 2026-06-27 15:04:42,060] Trial 12 finished with value: 0.9317767451508058 and parameters: {'n_estimators': 60, 'max_depth': 4, 'learning_rate': 0.09978551341356359, 'min_child_weight': 13, 'subsample': 0.6770920535070198, 'colsample_bytree': 0.723049278515438, 'gamma': 0.014891898198791116, 'lambda': 0.005005852939878152, 'alpha': 0.0010681845124340952}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:13:42,301] Trial 13 finished with value: 0.9317643095642303 and parameters: {'n_estimators': 60, 'max_depth': 4, 'learning_rate': 0.09937866864285416, 'min_child_weight': 13, 'subsample': 0.679900117133659, 'colsample_bytree': 0.7268791125532672, 'gamma': 0.01282886814995091, 'lambda': 0.005029065594955097, 'alpha': 0.0010128109985456319}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:21:07,063] Trial 14 finished with value: 0.9315983464127895 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.09922570958680274, 'min_child_weight': 14, 'subsample': 0.7395051602651459, 'colsample_bytree': 0.7273713590440929, 'gamma': 0.017223507076862505, 'lambda': 0.005738420110646089, 'alpha': 0.0017250134858345968}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:28:43,602] Trial 15 finished with value: 0.9303549898535319 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.07874935755116846, 'min_child_weight': 12, 'subsample': 0.6571680693178137, 'colsample_bytree': 0.7051621952009144, 'gamma': 0.0024623045145775423, 'lambda': 0.0033269823050458436, 'alpha': 0.0016630216216884331}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:38:51,161] Trial 16 finished with value: 0.9317642328599639 and parameters: {'n_estimators': 70, 'max_depth': 4, 'learning_rate': 0.07829098273642066, 'min_child_weight': 14, 'subsample': 0.7320422954348667, 'colsample_bytree': 0.7472753473586147, 'gamma': 0.008464348468480855, 'lambda': 0.005980128767251844, 'alpha': 0.0016432273143869598}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:48:44,796] Trial 17 finished with value: 0.9310062597187153 and parameters: {'n_estimators': 70, 'max_depth': 3, 'learning_rate': 0.09374863895003166, 'min_child_weight': 12, 'subsample': 0.6361545143197477, 'colsample_bytree': 0.6857724366219075, 'gamma': 0.020059053088759868, 'lambda': 0.003409835192735522, 'alpha': 0.0023907369698337694}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 15:56:20,515] Trial 18 finished with value: 0.931392796825769 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.08294784486668103, 'min_child_weight': 16, 'subsample': 0.7040893399286684, 'colsample_bytree': 0.7417747371294253, 'gamma': 0.03293027199832846, 'lambda': 0.0026695317009541556, 'alpha': 0.0012541872725396535}. Best is trial 12 with value: 0.9317767451508058.
[I 2026-06-27 16:04:06,900] Trial 19 finished with value: 0.9289226668820916 and parameters: {'n_estimators': 60, 'max_depth': 2, 'learning_rate': 0.07168477659592429, 'min_child_weight': 18, 'subsample': 0.7810770991226607, 'colsample_bytree': 0.7796181603217405, 'gamma': 0.00938915826297991, 'lambda': 0.006287041560777619, 'alpha': 0.002415947708092469}. Best is trial 12 with value: 0.9317767451508058.

In [19]:
print("Best Macro F1:")
print(study2.best_value)

print("\nBest Parameters:")
study2.best_params

Best Macro F1:
0.9317767451508058

Best Parameters:

{'n_estimators': 60,
 'max_depth': 4,
 'learning_rate': 0.09978551341356359,
 'min_child_weight': 13,
 'subsample': 0.6770920535070198,
 'colsample_bytree': 0.723049278515438,
 'gamma': 0.014891898198791116,
 'lambda': 0.005005852939878152,
 'alpha': 0.0010681845124340952}

In [32]:
study3 = optuna.create_study(direction="maximize")

study3.optimize(
    objective,
    n_trials=20,
    show_progress_bar=True
)

[I 2026-06-28 16:32:15,298] A new study created in memory with name: no-name-896ddb9c-ea71-483d-991a-56c97edc50bd

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-06-28 16:41:15,849] Trial 0 finished with value: 0.8866716985090222 and parameters: {'n_estimators': 40, 'max_depth': 5, 'learning_rate': 0.030405314361087867, 'min_child_weight': 16, 'subsample': 0.5396316067157367, 'colsample_bytree': 0.6757683575494218, 'gamma': 0.042499474760294656, 'lambda': 0.001289716648284723, 'alpha': 0.009448301684613816}. Best is trial 0 with value: 0.8866716985090222.
[I 2026-06-28 16:48:26,914] Trial 1 finished with value: 0.9299322640086267 and parameters: {'n_estimators': 30, 'max_depth': 5, 'learning_rate': 0.10103149519660198, 'min_child_weight': 12, 'subsample': 0.6396430875918652, 'colsample_bytree': 0.7092576907327343, 'gamma': 0.014174990998401632, 'lambda': 0.003182963845120234, 'alpha': 0.003024857292449281}. Best is trial 1 with value: 0.9299322640086267.
[I 2026-06-28 16:54:05,077] Trial 2 finished with value: 0.9214836517692181 and parameters: {'n_estimators': 20, 'max_depth': 7, 'learning_rate': 0.08300937685438435, 'min_child_weight': 15, 'subsample': 0.5681790785182663, 'colsample_bytree': 0.7006206182956336, 'gamma': 0.015936372437252013, 'lambda': 0.00990673830865092, 'alpha': 0.004986771849808988}. Best is trial 1 with value: 0.9299322640086267.
[I 2026-06-28 16:58:50,836] Trial 3 finished with value: 0.9315988342463667 and parameters: {'n_estimators': 20, 'max_depth': 6, 'learning_rate': 0.12694163124109353, 'min_child_weight': 13, 'subsample': 0.5037249813645249, 'colsample_bytree': 0.7438388797156009, 'gamma': 0.028774266985515745, 'lambda': 0.00925763429716094, 'alpha': 0.005998420230324246}. Best is trial 3 with value: 0.9315988342463667.
[I 2026-06-28 17:08:01,746] Trial 4 finished with value: 0.9315198420201666 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.09162836502647272, 'min_child_weight': 13, 'subsample': 0.5248213699972707, 'colsample_bytree': 0.7803765891850197, 'gamma': 0.0013787409106256199, 'lambda': 0.005772994179199008, 'alpha': 0.00852488067674844}. Best is trial 3 with value: 0.9315988342463667.
[I 2026-06-28 17:17:13,339] Trial 5 finished with value: 0.930002147780552 and parameters: {'n_estimators': 60, 'max_depth': 2, 'learning_rate': 0.10335965871163273, 'min_child_weight': 10, 'subsample': 0.6405370729613975, 'colsample_bytree': 0.7543594783550738, 'gamma': 0.007979081252540649, 'lambda': 0.0018449441123763739, 'alpha': 0.015185651811148605}. Best is trial 3 with value: 0.9315988342463667.
[I 2026-06-28 17:29:13,698] Trial 6 finished with value: 0.9343015195031166 and parameters: {'n_estimators': 70, 'max_depth': 7, 'learning_rate': 0.11304125728149036, 'min_child_weight': 14, 'subsample': 0.6954171391282954, 'colsample_bytree': 0.7664605073047757, 'gamma': 0.04965196677590019, 'lambda': 0.0012944686202150573, 'alpha': 0.004120840582543133}. Best is trial 6 with value: 0.9343015195031166.
[I 2026-06-28 17:33:29,878] Trial 7 finished with value: 0.9256620083628956 and parameters: {'n_estimators': 20, 'max_depth': 8, 'learning_rate': 0.08993577338769729, 'min_child_weight': 16, 'subsample': 0.6540142027564262, 'colsample_bytree': 0.6962594851424521, 'gamma': 0.028459301459290043, 'lambda': 0.004716387310488267, 'alpha': 0.0034766244682027866}. Best is trial 6 with value: 0.9343015195031166.
[I 2026-06-28 17:37:18,095] Trial 8 finished with value: 0.8749867116264409 and parameters: {'n_estimators': 20, 'max_depth': 6, 'learning_rate': 0.058845003376314445, 'min_child_weight': 11, 'subsample': 0.7575492763571381, 'colsample_bytree': 0.6531423755453911, 'gamma': 0.03258369002764328, 'lambda': 0.0027719186397767792, 'alpha': 0.0012365313643812558}. Best is trial 6 with value: 0.9343015195031166.
[I 2026-06-28 17:41:01,192] Trial 9 finished with value: 0.7749400952383424 and parameters: {'n_estimators': 20, 'max_depth': 6, 'learning_rate': 0.041832092699086484, 'min_child_weight': 16, 'subsample': 0.7276692758961256, 'colsample_bytree': 0.7504722016536526, 'gamma': 0.006049696366752694, 'lambda': 0.001178185931193481, 'alpha': 0.01535184223104357}. Best is trial 6 with value: 0.9343015195031166.
[I 2026-06-28 17:51:01,150] Trial 10 finished with value: 0.9304719221237632 and parameters: {'n_estimators': 70, 'max_depth': 2, 'learning_rate': 0.1474414783868833, 'min_child_weight': 18, 'subsample': 0.8153783716186046, 'colsample_bytree': 0.7895543035426972, 'gamma': 0.04717548692557171, 'lambda': 0.0020645484841166134, 'alpha': 0.0014321026414167073}. Best is trial 6 with value: 0.9343015195031166.
[I 2026-06-28 18:03:55,574] Trial 11 finished with value: 0.935406975585528 and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.1349325608942457, 'min_child_weight': 14, 'subsample': 0.5961850967666071, 'colsample_bytree': 0.742279400803029, 'gamma': 0.03472355046243029, 'lambda': 0.0074299131797073556, 'alpha': 0.0049279110449704224}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 18:15:54,850] Trial 12 finished with value: 0.9353161029808004 and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.12774061286901936, 'min_child_weight': 14, 'subsample': 0.7092718180010462, 'colsample_bytree': 0.7302713389645613, 'gamma': 0.04022177222040117, 'lambda': 0.005385265203691832, 'alpha': 0.002318538245362029}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 18:26:39,262] Trial 13 finished with value: 0.9353189850724762 and parameters: {'n_estimators': 60, 'max_depth': 8, 'learning_rate': 0.1496736100150075, 'min_child_weight': 14, 'subsample': 0.5822457487018917, 'colsample_bytree': 0.7239432808465877, 'gamma': 0.03840166819340015, 'lambda': 0.00609299235626753, 'alpha': 0.0016692256397731167}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 18:35:49,453] Trial 14 finished with value: 0.9349030097172563 and parameters: {'n_estimators': 50, 'max_depth': 8, 'learning_rate': 0.14585887117884805, 'min_child_weight': 14, 'subsample': 0.5827703150710817, 'colsample_bytree': 0.7251395528918767, 'gamma': 0.03463348302900846, 'lambda': 0.007146272945045066, 'alpha': 0.0019278588132773352}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 18:46:28,912] Trial 15 finished with value: 0.9342106226893824 and parameters: {'n_estimators': 60, 'max_depth': 7, 'learning_rate': 0.12830473863114053, 'min_child_weight': 18, 'subsample': 0.5944386015741042, 'colsample_bytree': 0.7236671359518534, 'gamma': 0.021601110189759284, 'lambda': 0.004123388456305788, 'alpha': 0.0010682717230075986}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 18:57:33,057] Trial 16 finished with value: 0.9348982742191663 and parameters: {'n_estimators': 60, 'max_depth': 8, 'learning_rate': 0.13880269516350946, 'min_child_weight': 12, 'subsample': 0.5965837259668065, 'colsample_bytree': 0.6834527721709487, 'gamma': 0.03931851118960633, 'lambda': 0.007662889844734091, 'alpha': 0.002344311683632902}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 19:06:32,248] Trial 17 finished with value: 0.9337725401055129 and parameters: {'n_estimators': 50, 'max_depth': 7, 'learning_rate': 0.1168005481665276, 'min_child_weight': 15, 'subsample': 0.6134067486052848, 'colsample_bytree': 0.7392873635447731, 'gamma': 0.023803442599305114, 'lambda': 0.006843244036869617, 'alpha': 0.007226534844735159}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 19:17:34,907] Trial 18 finished with value: 0.9351190050855445 and parameters: {'n_estimators': 60, 'max_depth': 8, 'learning_rate': 0.13788889787598005, 'min_child_weight': 17, 'subsample': 0.5523333728050579, 'colsample_bytree': 0.773154680468356, 'gamma': 0.03537631361758089, 'lambda': 0.003918859241014482, 'alpha': 0.0017476701854251715}. Best is trial 11 with value: 0.935406975585528.
[I 2026-06-28 19:29:29,648] Trial 19 finished with value: 0.9347665685151565 and parameters: {'n_estimators': 70, 'max_depth': 7, 'learning_rate': 0.14989214463219314, 'min_child_weight': 13, 'subsample': 0.6517047275075609, 'colsample_bytree': 0.7970187073741496, 'gamma': 0.044199705313598986, 'lambda': 0.006222995396416867, 'alpha': 0.01134521538349792}. Best is trial 11 with value: 0.935406975585528.

In [16]:
fig = optuna.visualization.plot_optimization_history(study)
fig.show()

In [17]:
optuna.visualization.plot_parallel_coordinate(study)

In [18]:
optuna.visualization.plot_slice(study)

In [19]:
optuna.visualization.plot_param_importances(study)

In [33]:
best_params = study3.best_params
best_params

{'n_estimators': 70,
 'max_depth': 8,
 'learning_rate': 0.1349325608942457,
 'min_child_weight': 14,
 'subsample': 0.5961850967666071,
 'colsample_bytree': 0.742279400803029,
 'gamma': 0.03472355046243029,
 'lambda': 0.0074299131797073556,
 'alpha': 0.0049279110449704224}

In [8]:
best_params ={'n_estimators': 60,
 'max_depth': 4,
 'learning_rate': 0.09978551341356359,
 'min_child_weight': 13,
 'subsample': 0.6770920535070198,
 'colsample_bytree': 0.723049278515438,
 'gamma': 0.014891898198791116,
 'lambda': 0.005005852939878152,
 'alpha': 0.0010681845124340952
}

In [8]:

import joblib

final_model =  joblib.load('lgb_model_NAS.pkl')

final_model.fit(
    X_train,
    y_train
)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.359926 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 916
[LightGBM] [Info] Number of data points in the train set: 20988361, number of used features: 7
[LightGBM] [Info] Start training from score -0.227400
[LightGBM] [Info] Start training from score -2.977051
[LightGBM] [Info] Start training from score -1.880887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(colsample_bytree=0.7551178667909587,
               learning_rate=0.05100951282436649, max_depth=4,
               min_child_samples=34, min_split_gain=0.006075023874388366,
               n_estimators=30, num_class=3, num_leaves=66,
               objective='multiclass', random_state=42,
               reg_alpha=0.12087874480114016, reg_lambda=0.11024868381878898,
               subsample=0.897944887767238)

In [9]:
y_pred1 = final_model.predict(
    X_train
)
y_pred = final_model.predict(
    X_test
)

In [10]:
print("TRAIN RESULTS")
print(
    classification_report(
        y_train,
        y_pred1
    )
)

macro_f1 = f1_score(
    y_train,
    y_pred1,
    average="macro"
)

print(
    "Train Macro F1:",
    macro_f1
)
print()
print("TEST RESULTS")
print(
    classification_report(
        y_test,
        y_pred
    )
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print(
    "Test Macro F1:",
    macro_f1
)

TRAIN RESULTS
              precision    recall  f1-score   support

           0       1.00      1.00      1.00  16719377
           1       0.83      0.87      0.85   1069207
           2       0.94      0.94      0.94   3199777

    accuracy                           0.98  20988361
   macro avg       0.92      0.94      0.93  20988361
weighted avg       0.98      0.98      0.98  20988361

Train Macro F1: 0.9296942668815399

TEST RESULTS
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    956898
           1       0.81      0.89      0.85     75876
           2       0.93      0.88      0.91    149414

    accuracy                           0.98   1182188
   macro avg       0.91      0.92      0.92   1182188
weighted avg       0.98      0.98      0.98   1182188

Test Macro F1: 0.9176816948829142

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    956898
           1       0.80      0.89      0.84     75876
           2       0.93      0.88      0.91    149414

    accuracy                           0.98   1182188
   macro avg       0.91      0.92      0.92   1182188
weighted avg       0.98      0.98      0.98   1182188

Test Macro F1: 0.915229630211178

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[954809    140   1949]
 [   196  65699   9981]
 [   898  16878 131638]]

In [5]:
best_params={'n_estimators': 400,
 'max_depth': 11,
 'learning_rate': 0.160150368880871,
 'subsample': 0.6798136276263954,
 'colsample_bytree': 0.7243238118279334,
 'min_child_weight': 14,
 'gamma': 0.014344298946540327,
 'lambda': 0.0027281560811716794,
 'alpha': 0.007634436209519525,
 'grow_policy': 'lossguide'}

In [2]:
from sklearn.metrics import f1_score
import copy
import xgboost as xgb
import pandas as pd

def tune_one_parameter(param_name, values):

    results = []

    for value in values:

        params = copy.deepcopy(best_params)
        params[param_name] = value

        model = xgb.XGBClassifier(
            objective="multi:softprob",
            num_class=3,
            tree_method="hist",
            random_state=42,
            n_jobs=-1,
            **params
        )

        model.fit(X_train, y_train)

        # Train prediction
        train_pred = model.predict(X_train)
        train_f1 = f1_score(
            y_train,
            train_pred,
            average="macro"
        )

        # Test prediction
        test_pred = model.predict(X_test)
        test_f1 = f1_score(
            y_test,
            test_pred,
            average="macro"
        )

        gap = train_f1 - test_f1

        results.append([value, train_f1, test_f1, gap])

        print(
            f"{param_name}={value} | "
            f"Train={train_f1:.4f} | "
            f"Test={test_f1:.4f} | "
            f"Gap={gap:.4f}"
        )

In [32]:
depth_results = tune_one_parameter(
    "max_depth",
    [8,9,10,11,12,13,14]
)

depth_results

max_depth=8 | Train=0.9415 | Test=0.9109 | Gap=0.0306
max_depth=9 | Train=0.9432 | Test=0.9101 | Gap=0.0331
max_depth=10 | Train=0.9454 | Test=0.9095 | Gap=0.0360
max_depth=11 | Train=0.9477 | Test=0.9085 | Gap=0.0392
max_depth=12 | Train=0.9500 | Test=0.9077 | Gap=0.0423
max_depth=13 | Train=0.9527 | Test=0.9072 | Gap=0.0455
max_depth=14 | Train=0.9555 | Test=0.9062 | Gap=0.0493

   max_depth  Train Macro F1  Test Macro F1  Generalization Gap
0          8        0.941470       0.910851            0.030619
1          9        0.943193       0.910073            0.033119
2         10        0.945434       0.909481            0.035953
3         11        0.947651       0.908489            0.039162
4         12        0.950034       0.907696            0.042339
5         13        0.952689       0.907198            0.045491
6         14        0.955481       0.906205            0.049276

In [33]:
tune_one_parameter(
    "max_depth",
    [4,5,6,7]
)

max_depth=4 | Train=0.9352 | Test=0.9150 | Gap=0.0202
max_depth=5 | Train=0.9367 | Test=0.9136 | Gap=0.0231
max_depth=6 | Train=0.9381 | Test=0.9130 | Gap=0.0251
max_depth=7 | Train=0.9396 | Test=0.9119 | Gap=0.0277

   max_depth  Train Macro F1  Test Macro F1  Generalization Gap
0          4        0.935221       0.915034            0.020186
1          5        0.936681       0.913564            0.023117
2          6        0.938146       0.913019            0.025127
3          7        0.939635       0.911902            0.027732

In [ ]:
tune_one_parameter(
    "min_child_weight",
    [12,13,15,16]
)

max_depth=1 | Train=0.9307 | Test=0.9176 | Gap=0.0131
max_depth=2 | Train=0.9327 | Test=0.9164 | Gap=0.0163
max_depth=3 | Train=0.9339 | Test=0.9156 | Gap=0.0183

   max_depth  Train Macro F1  Test Macro F1  Generalization Gap
0          1        0.930686       0.917569            0.013117
1          2        0.932685       0.916365            0.016319
2          3        0.933873       0.915610            0.018262

In [35]:
tune_one_parameter(
    "min_child_weight",
    [12,13,15,16]
)

min_child_weight=12 | Train=0.9479 | Test=0.9085 | Gap=0.0394
min_child_weight=13 | Train=0.9479 | Test=0.9085 | Gap=0.0393
min_child_weight=15 | Train=0.9474 | Test=0.9086 | Gap=0.0388
min_child_weight=16 | Train=0.9474 | Test=0.9084 | Gap=0.0389

   min_child_weight  Train Macro F1  Test Macro F1  Generalization Gap
0                12        0.947920       0.908512            0.039408
1                13        0.947855       0.908523            0.039332
2                15        0.947421       0.908636            0.038785
3                16        0.947361       0.908419            0.038942

In [11]:
tune_one_parameter(
    "n_estimators",
    [350,420,470]
)

n_estimators=350 | Train=0.9468 | Test=0.9088 | Gap=0.0380
n_estimators=420 | Train=0.9480 | Test=0.9082 | Gap=0.0397

KeyboardInterrupt:

In [12]:
tune_one_parameter(
    "n_estimators",
    [200,250,300]
)

n_estimators=200 | Train=0.9439 | Test=0.9100 | Gap=0.0340
n_estimators=250 | Train=0.9450 | Test=0.9096 | Gap=0.0354
n_estimators=300 | Train=0.9461 | Test=0.9090 | Gap=0.0370

In [13]:
tune_one_parameter(
    "n_estimators",
    [50,100,150]
)

n_estimators=50 | Train=0.9386 | Test=0.9137 | Gap=0.0249
n_estimators=100 | Train=0.9409 | Test=0.9119 | Gap=0.0291
n_estimators=150 | Train=0.9425 | Test=0.9109 | Gap=0.0316

In [14]:
tune_one_parameter(
    "subsample",
    [0.51,0.73,0.82]
)

subsample=0.51 | Train=0.9469 | Test=0.9086 | Gap=0.0383
subsample=0.73 | Train=0.9477 | Test=0.9083 | Gap=0.0393
subsample=0.82 | Train=0.9477 | Test=0.9087 | Gap=0.0390

In [16]:
tune_one_parameter(
    "lambda",
    [0.0011,0.0021,0.0034]
)

lambda=0.0011 | Train=0.9476 | Test=0.9085 | Gap=0.0391
lambda=0.0021 | Train=0.9477 | Test=0.9085 | Gap=0.0392
lambda=0.0034 | Train=0.9476 | Test=0.9085 | Gap=0.0392